using System;
using System.Collections;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using Profunia.Inventory.Desktop.ClassFiles.SP;using Profunia.Inventory.Desktop.ClassFiles.Info;using Profunia.Inventory.Desktop.ClassFiles.General;using System.Windows.Forms;
namespace Profunia.Inventory.Desktop.Transactions
{
    partial class frmPOS
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            DataGridViewCellStyle dataGridViewCellStyle32 = new DataGridViewCellStyle();
            DataGridViewCellStyle dataGridViewCellStyle31 = new DataGridViewCellStyle();
            DataGridViewCellStyle dataGridViewCellStyle30 = new DataGridViewCellStyle();
            DataGridViewCellStyle dataGridViewCellStyle29 = new DataGridViewCellStyle();
            DataGridViewCellStyle dataGridViewCellStyle28 = new DataGridViewCellStyle();
            DataGridViewCellStyle dataGridViewCellStyle27 = new DataGridViewCellStyle();
            DataGridViewCellStyle dataGridViewCellStyle26 = new DataGridViewCellStyle();
            DataGridViewCellStyle dataGridViewCellStyle25 = new DataGridViewCellStyle();
            DataGridViewCellStyle dataGridViewCellStyle24 = new DataGridViewCellStyle();
            DataGridViewCellStyle dataGridViewCellStyle23 = new DataGridViewCellStyle();
            DataGridViewCellStyle dataGridViewCellStyle22 = new DataGridViewCellStyle();
            DataGridViewCellStyle dataGridViewCellStyle21 = new DataGridViewCellStyle();
            DataGridViewCellStyle dataGridViewCellStyle20 = new DataGridViewCellStyle();
            DataGridViewCellStyle dataGridViewCellStyle19 = new DataGridViewCellStyle();
            DataGridViewCellStyle dataGridViewCellStyle18 = new DataGridViewCellStyle();
            DataGridViewCellStyle dataGridViewCellStyle17 = new DataGridViewCellStyle();
            DataGridViewCellStyle dataGridViewCellStyle16 = new DataGridViewCellStyle();
            ComponentResourceManager resources = new ComponentResourceManager(typeof(frmPOS));
            btnNewSalesMan = new Button();
            txtVoucherNo = new TextBox();
            lblVoucherNo = new Label();
            btnSave = new Button();
            cmbCashOrParty = new ComboBox();
            btnClose = new Button();
            btnDelete = new Button();
            btnClear = new Button();
            lblCashOrParty = new Label();
            dgvPointOfSales = new DataGridView();
            dgvtxtSlNo = new DataGridViewTextBoxColumn();
            rowId = new DataGridViewTextBoxColumn();
            dgvtxtProductId = new DataGridViewTextBoxColumn();
            dgvtxtProductCode = new DataGridViewTextBoxColumn();
            dgvtxtProductName = new DataGridViewTextBoxColumn();
            dgvtxtQuantity = new DataGridViewTextBoxColumn();
            dgvtxtUnit = new DataGridViewTextBoxColumn();
            dgvtxtRate = new DataGridViewTextBoxColumn();
            dgvtxtGrossValue = new DataGridViewTextBoxColumn();
            dgvtxtDiscount = new DataGridViewTextBoxColumn();
            dgvtxtNetAmount = new DataGridViewTextBoxColumn();
            dgvtxtTaxPercentage = new DataGridViewTextBoxColumn();
            dgvtxttaxid = new DataGridViewTextBoxColumn();
            dgvtxtTaxAmount = new DataGridViewTextBoxColumn();
            dgvtxtTotalAmount = new DataGridViewTextBoxColumn();
            dgvtxtBatchId = new DataGridViewTextBoxColumn();
            dgvtxtBatchno = new DataGridViewTextBoxColumn();
            dgvtxtRackId = new DataGridViewTextBoxColumn();
            dgvtxtRackName = new DataGridViewTextBoxColumn();
            dgvtxtGodownId = new DataGridViewTextBoxColumn();
            dgvtxtGodownName = new DataGridViewTextBoxColumn();
            dgvtxtUnitId = new DataGridViewTextBoxColumn();
            dgvtxtunitconversionId = new DataGridViewTextBoxColumn();
            dgvtxtBarcode = new DataGridViewTextBoxColumn();
            dgvtxtDiscountPercentage = new DataGridViewTextBoxColumn();
            dgvtxtSalesDetailsId = new DataGridViewTextBoxColumn();
            lblDate = new Label();
            cmbSalesMan = new ComboBox();
            lblSalesMan = new Label();
            btnNewLedger = new Button();
            btnNewSalesAccount = new Button();
            cmbSalesAccount = new ComboBox();
            lblsalesAccount = new Label();
            btnNewCounter = new Button();
            cmbCounter = new ComboBox();
            lblCounter = new Label();
            gbxDetails = new GroupBox();
            groupBox1 = new GroupBox();
            lblUnitConversion = new Label();
            lblUnitConversionRate = new Label();
            lblUnitConversionId = new Label();
            btnAdd = new Button();
            txtAmount = new TextBox();
            lblAmount = new Label();
            txtDiscountAmount = new TextBox();
            lblDiscountAmt = new Label();
            txtDiscountPercentage = new TextBox();
            lblDiscountPercentage = new Label();
            txtNetAmount = new TextBox();
            lblnetAmount = new Label();
            txtTaxAmount = new TextBox();
            lblTaxAmount = new Label();
            cmbTax = new ComboBox();
            lblTax = new Label();
            txtGrossValue = new TextBox();
            lblGrossValue = new Label();
            txtRate = new TextBox();
            lblRate = new Label();
            cmbUnit = new ComboBox();
            lblUnit = new Label();
            txtQuantity = new TextBox();
            lblQuantity = new Label();
            cmbBatch = new ComboBox();
            lblBatch = new Label();
            cmbRack = new ComboBox();
            lblRack = new Label();
            cmbGodown = new ComboBox();
            lblGodown = new Label();
            cmbItem = new ComboBox();
            lblItem = new Label();
            txtProductCode = new TextBox();
            lblProductcode = new Label();
            txtBarcode = new TextBox();
            lblBarcode = new Label();
            lnklblRemove = new LinkLabel();
            txtTotalAmount = new TextBox();
            lblTotal = new Label();
            txtBillDiscount = new TextBox();
            lblDiscount = new Label();
            txtGrandTotal = new TextBox();
            lblGrandTotal = new Label();
            dgvPOSTax = new DataGridView();
            dgvtxtSINO = new DataGridViewTextBoxColumn();
            dgvtxtTaxLedgerId = new DataGridViewTextBoxColumn();
            dgvtxtTaxName = new DataGridViewTextBoxColumn();
            dgvtxtTaxAmt = new DataGridViewTextBoxColumn();
            dgvtxttaxrate = new DataGridViewTextBoxColumn();
            dgvtxttax = new DataGridViewTextBoxColumn();
            dgvtxtTaxApplicableOn = new DataGridViewTextBoxColumn();
            dgvtxttaxCalculateMode = new DataGridViewTextBoxColumn();
            Column2 = new DataGridViewTextBoxColumn();
            temp = new DataGridViewTextBoxColumn();
            lblLedgerTotal = new Label();
            cbxPrintAfterSave = new CheckBox();
            lblTaxTotalAmount = new Label();
            txtNarration = new TextBox();
            label26 = new Label();
            gbxAmountDetails = new GroupBox();
            groupBox2 = new GroupBox();
            txtBalance = new TextBox();
            lblBalance = new Label();
            txtPaidAmount = new TextBox();
            lblPaidAmount = new Label();
            cmbPricingLevel = new ComboBox();
            lblPricingLevel = new Label();
            dtpDate = new DateTimePicker();
            txtDate = new TextBox();
            label1 = new Label();
            label2 = new Label();
            label3 = new Label();
            ((ISupportInitialize)dgvPointOfSales).BeginInit();
            gbxDetails.SuspendLayout();
            ((ISupportInitialize)dgvPOSTax).BeginInit();
            gbxAmountDetails.SuspendLayout();
            base.SuspendLayout();
            btnNewSalesMan.BackColor = Color.Gray;
            btnNewSalesMan.BackgroundImageLayout = ImageLayout.None;
            btnNewSalesMan.FlatAppearance.BorderSize = 0;
            btnNewSalesMan.FlatStyle = FlatStyle.Flat;
            btnNewSalesMan.Font = new Font("Bauhaus 93", 8.25f, FontStyle.Regular, GraphicsUnit.Point, 0);
            btnNewSalesMan.ForeColor = Color.White;
            btnNewSalesMan.Location = new Point(953, 14);
            btnNewSalesMan.Name = "btnNewSalesMan";
            btnNewSalesMan.Size = new Size(21, 20);
            btnNewSalesMan.TabIndex = 4;
            btnNewSalesMan.Text = "+";
            btnNewSalesMan.UseVisualStyleBackColor = false;
            btnNewSalesMan.Click += btnNewSalesMan_Click;
            txtVoucherNo.Location = new Point(129, 14);
            txtVoucherNo.Margin = new Padding(5, 5, 5, 0);
            txtVoucherNo.Name = "txtVoucherNo";
            txtVoucherNo.Size = new Size(142, 20);
            txtVoucherNo.TabIndex = 0;
            txtVoucherNo.KeyDown += txtVoucherNo_KeyDown;
            lblVoucherNo.AutoSize = true;
            lblVoucherNo.BackColor = Color.Transparent;
            lblVoucherNo.ForeColor = Color.Black;
            lblVoucherNo.Location = new Point(20, 14);
            lblVoucherNo.Margin = new Padding(5);
            lblVoucherNo.Name = "lblVoucherNo";
            lblVoucherNo.Size = new Size(67, 13);
            lblVoucherNo.TabIndex = 1119;
            lblVoucherNo.Text = "Voucher No.";
            btnSave.BackColor = Color.LightSteelBlue;
            btnSave.FlatAppearance.BorderSize = 0;
            btnSave.FlatStyle = FlatStyle.Flat;
            btnSave.ForeColor = Color.Black;
            btnSave.Location = new Point(616, 526);
            btnSave.Name = "btnSave";
            btnSave.Size = new Size(85, 27);
            btnSave.TabIndex = 17;
            btnSave.Text = "Save";
            btnSave.UseVisualStyleBackColor = false;
            btnSave.Click += btnSave_Click;
            btnSave.KeyDown += btnSave_KeyDown;
            cmbCashOrParty.DropDownStyle = ComboBoxStyle.DropDownList;
            cmbCashOrParty.FormattingEnabled = true;
            cmbCashOrParty.Location = new Point(129, 39);
            cmbCashOrParty.Margin = new Padding(5);
            cmbCashOrParty.Name = "cmbCashOrParty";
            cmbCashOrParty.Size = new Size(242, 21);
            cmbCashOrParty.TabIndex = 5;
            cmbCashOrParty.KeyDown += cmbCashOrParty_KeyDown;
            btnClose.BackColor = Color.LightSteelBlue;
            btnClose.FlatAppearance.BorderSize = 0;
            btnClose.FlatStyle = FlatStyle.Flat;
            btnClose.ForeColor = Color.Black;
            btnClose.Location = new Point(889, 526);
            btnClose.Name = "btnClose";
            btnClose.Size = new Size(85, 27);
            btnClose.TabIndex = 20;
            btnClose.Text = "Close";
            btnClose.UseVisualStyleBackColor = false;
            btnClose.Click += btnClose_Click;
            btnDelete.BackColor = Color.Salmon;
            btnDelete.FlatAppearance.BorderSize = 0;
            btnDelete.FlatStyle = FlatStyle.Flat;
            btnDelete.ForeColor = Color.Black;
            btnDelete.Location = new Point(798, 526);
            btnDelete.Name = "btnDelete";
            btnDelete.Size = new Size(85, 27);
            btnDelete.TabIndex = 19;
            btnDelete.Text = "Delete";
            btnDelete.UseVisualStyleBackColor = false;
            btnDelete.Click += btnDelete_Click;
            btnClear.BackColor = Color.LightSteelBlue;
            btnClear.FlatAppearance.BorderSize = 0;
            btnClear.FlatStyle = FlatStyle.Flat;
            btnClear.ForeColor = Color.Black;
            btnClear.Location = new Point(707, 526);
            btnClear.Name = "btnClear";
            btnClear.Size = new Size(85, 27);
            btnClear.TabIndex = 18;
            btnClear.Text = "Clear";
            btnClear.UseVisualStyleBackColor = false;
            btnClear.Click += btnClear_Click;
            lblCashOrParty.AutoSize = true;
            lblCashOrParty.BackColor = Color.Transparent;
            lblCashOrParty.ForeColor = Color.Black;
            lblCashOrParty.Location = new Point(20, 39);
            lblCashOrParty.Margin = new Padding(5);
            lblCashOrParty.Name = "lblCashOrParty";
            lblCashOrParty.Size = new Size(66, 13);
            lblCashOrParty.TabIndex = 1113;
            lblCashOrParty.Text = "Cash / Party";
            dgvPointOfSales.AllowUserToAddRows = false;
            dgvPointOfSales.AllowUserToDeleteRows = false;
            dgvPointOfSales.AllowUserToResizeColumns = false;
            dgvPointOfSales.AllowUserToResizeRows = false;
            dgvPointOfSales.AutoSizeColumnsMode = DataGridViewAutoSizeColumnsMode.Fill;
            dgvPointOfSales.BackgroundColor = Color.White;
            dgvPointOfSales.ColumnHeadersBorderStyle = DataGridViewHeaderBorderStyle.Single;
            dataGridViewCellStyle32.Alignment = DataGridViewContentAlignment.MiddleLeft;
            dataGridViewCellStyle32.BackColor = Color.DimGray;
            dataGridViewCellStyle32.Font = new Font("Arial", 9f, FontStyle.Bold, GraphicsUnit.Point, 0);
            dataGridViewCellStyle32.ForeColor = Color.White;
            dataGridViewCellStyle32.SelectionBackColor = Color.Silver;
            dataGridViewCellStyle32.SelectionForeColor = Color.White;
            dataGridViewCellStyle32.WrapMode = DataGridViewTriState.True;
            dgvPointOfSales.ColumnHeadersDefaultCellStyle = dataGridViewCellStyle32;
            dgvPointOfSales.ColumnHeadersHeight = 35;
            dgvPointOfSales.ColumnHeadersHeightSizeMode = DataGridViewColumnHeadersHeightSizeMode.DisableResizing;
            dgvPointOfSales.Columns.AddRange(dgvtxtSlNo, rowId, dgvtxtProductId, dgvtxtProductCode, dgvtxtProductName, dgvtxtQuantity, dgvtxtUnit, dgvtxtRate, dgvtxtGrossValue, dgvtxtDiscount, dgvtxtNetAmount, dgvtxtTaxPercentage, dgvtxttaxid, dgvtxtTaxAmount, dgvtxtTotalAmount, dgvtxtBatchId, dgvtxtBatchno, dgvtxtRackId, dgvtxtRackName, dgvtxtGodownId, dgvtxtGodownName, dgvtxtUnitId, dgvtxtunitconversionId, dgvtxtBarcode, dgvtxtDiscountPercentage, dgvtxtSalesDetailsId);
            dataGridViewCellStyle31.Alignment = DataGridViewContentAlignment.MiddleLeft;
            dataGridViewCellStyle31.BackColor = Color.FromArgb(224, 224, 224);
            dataGridViewCellStyle31.Font = new Font("Microsoft Sans Serif", 8.25f, FontStyle.Regular, GraphicsUnit.Point, 0);
            dataGridViewCellStyle31.ForeColor = Color.Black;
            dataGridViewCellStyle31.SelectionBackColor = Color.DarkGray;
            dataGridViewCellStyle31.SelectionForeColor = Color.Black;
            dataGridViewCellStyle31.WrapMode = DataGridViewTriState.False;
            dgvPointOfSales.DefaultCellStyle = dataGridViewCellStyle31;
            dgvPointOfSales.EnableHeadersVisualStyles = false;
            dgvPointOfSales.GridColor = Color.DimGray;
            dgvPointOfSales.Location = new Point(18, 252);
            dgvPointOfSales.Margin = new Padding(3, 3, 3, 10);
            dgvPointOfSales.MultiSelect = false;
            dgvPointOfSales.Name = "dgvPointOfSales";
            dgvPointOfSales.ReadOnly = true;
            dgvPointOfSales.RowHeadersVisible = false;
            dgvPointOfSales.SelectionMode = DataGridViewSelectionMode.CellSelect;
            dgvPointOfSales.Size = new Size(956, 158);
            dgvPointOfSales.TabIndex = 12;
            dgvPointOfSales.TabStop = false;
            dgvPointOfSales.CellDoubleClick += dgvPointOfSales_CellDoubleClick;
            dgvPointOfSales.RowsAdded += dgvPointOfSales_RowsAdded;
            dgvtxtSlNo.HeaderText = "Sl No";
            dgvtxtSlNo.Name = "dgvtxtSlNo";
            dgvtxtSlNo.ReadOnly = true;
            dgvtxtSlNo.SortMode = DataGridViewColumnSortMode.NotSortable;
            rowId.HeaderText = "rowId";
            rowId.Name = "rowId";
            rowId.ReadOnly = true;
            rowId.SortMode = DataGridViewColumnSortMode.NotSortable;
            rowId.Visible = false;
            dgvtxtProductId.DataPropertyName = "productId";
            dgvtxtProductId.HeaderText = "ProductId";
            dgvtxtProductId.Name = "dgvtxtProductId";
            dgvtxtProductId.ReadOnly = true;
            dgvtxtProductId.SortMode = DataGridViewColumnSortMode.NotSortable;
            dgvtxtProductId.Visible = false;
            dataGridViewCellStyle30.Alignment = DataGridViewContentAlignment.TopLeft;
            dgvtxtProductCode.DefaultCellStyle = dataGridViewCellStyle30;
            dgvtxtProductCode.HeaderText = "Product Code";
            dgvtxtProductCode.Name = "dgvtxtProductCode";
            dgvtxtProductCode.ReadOnly = true;
            dgvtxtProductCode.SortMode = DataGridViewColumnSortMode.NotSortable;
            dataGridViewCellStyle29.Alignment = DataGridViewContentAlignment.TopLeft;
            dgvtxtProductName.DefaultCellStyle = dataGridViewCellStyle29;
            dgvtxtProductName.HeaderText = "Product";
            dgvtxtProductName.Name = "dgvtxtProductName";
            dgvtxtProductName.ReadOnly = true;
            dgvtxtProductName.SortMode = DataGridViewColumnSortMode.NotSortable;
            dataGridViewCellStyle28.Alignment = DataGridViewContentAlignment.MiddleRight;
            dgvtxtQuantity.DefaultCellStyle = dataGridViewCellStyle28;
            dgvtxtQuantity.HeaderText = "Qty.";
            dgvtxtQuantity.MinimumWidth = 8;
            dgvtxtQuantity.Name = "dgvtxtQuantity";
            dgvtxtQuantity.ReadOnly = true;
            dgvtxtQuantity.SortMode = DataGridViewColumnSortMode.NotSortable;
            dataGridViewCellStyle27.Alignment = DataGridViewContentAlignment.TopLeft;
            dgvtxtUnit.DefaultCellStyle = dataGridViewCellStyle27;
            dgvtxtUnit.HeaderText = "Unit";
            dgvtxtUnit.Name = "dgvtxtUnit";
            dgvtxtUnit.ReadOnly = true;
            dgvtxtUnit.SortMode = DataGridViewColumnSortMode.NotSortable;
            dataGridViewCellStyle26.Alignment = DataGridViewContentAlignment.MiddleRight;
            dgvtxtRate.DefaultCellStyle = dataGridViewCellStyle26;
            dgvtxtRate.HeaderText = "Rate";
            dgvtxtRate.Name = "dgvtxtRate";
            dgvtxtRate.ReadOnly = true;
            dgvtxtRate.SortMode = DataGridViewColumnSortMode.NotSortable;
            dataGridViewCellStyle25.Alignment = DataGridViewContentAlignment.MiddleRight;
            dgvtxtGrossValue.DefaultCellStyle = dataGridViewCellStyle25;
            dgvtxtGrossValue.HeaderText = "Gross Value";
            dgvtxtGrossValue.Name = "dgvtxtGrossValue";
            dgvtxtGrossValue.ReadOnly = true;
            dgvtxtGrossValue.SortMode = DataGridViewColumnSortMode.NotSortable;
            dataGridViewCellStyle24.Alignment = DataGridViewContentAlignment.MiddleRight;
            dgvtxtDiscount.DefaultCellStyle = dataGridViewCellStyle24;
            dgvtxtDiscount.HeaderText = "Discount";
            dgvtxtDiscount.Name = "dgvtxtDiscount";
            dgvtxtDiscount.ReadOnly = true;
            dgvtxtDiscount.SortMode = DataGridViewColumnSortMode.NotSortable;
            dataGridViewCellStyle23.Alignment = DataGridViewContentAlignment.MiddleRight;
            dgvtxtNetAmount.DefaultCellStyle = dataGridViewCellStyle23;
            dgvtxtNetAmount.HeaderText = "NetAmount";
            dgvtxtNetAmount.Name = "dgvtxtNetAmount";
            dgvtxtNetAmount.ReadOnly = true;
            dgvtxtNetAmount.SortMode = DataGridViewColumnSortMode.NotSortable;
            dataGridViewCellStyle22.Alignment = DataGridViewContentAlignment.TopLeft;
            dgvtxtTaxPercentage.DefaultCellStyle = dataGridViewCellStyle22;
            dgvtxtTaxPercentage.HeaderText = "Tax";
            dgvtxtTaxPercentage.Name = "dgvtxtTaxPercentage";
            dgvtxtTaxPercentage.ReadOnly = true;
            dgvtxtTaxPercentage.SortMode = DataGridViewColumnSortMode.NotSortable;
            dgvtxttaxid.HeaderText = "Tax";
            dgvtxttaxid.Name = "dgvtxttaxid";
            dgvtxttaxid.ReadOnly = true;
            dgvtxttaxid.SortMode = DataGridViewColumnSortMode.NotSortable;
            dgvtxttaxid.Visible = false;
            dataGridViewCellStyle21.Alignment = DataGridViewContentAlignment.MiddleRight;
            dgvtxtTaxAmount.DefaultCellStyle = dataGridViewCellStyle21;
            dgvtxtTaxAmount.HeaderText = "Tax Amount";
            dgvtxtTaxAmount.Name = "dgvtxtTaxAmount";
            dgvtxtTaxAmount.ReadOnly = true;
            dgvtxtTaxAmount.SortMode = DataGridViewColumnSortMode.NotSortable;
            dataGridViewCellStyle20.Alignment = DataGridViewContentAlignment.MiddleRight;
            dgvtxtTotalAmount.DefaultCellStyle = dataGridViewCellStyle20;
            dgvtxtTotalAmount.HeaderText = "Amount";
            dgvtxtTotalAmount.Name = "dgvtxtTotalAmount";
            dgvtxtTotalAmount.ReadOnly = true;
            dgvtxtTotalAmount.SortMode = DataGridViewColumnSortMode.NotSortable;
            dgvtxtBatchId.DataPropertyName = "batchId";
            dgvtxtBatchId.HeaderText = "batchId";
            dgvtxtBatchId.Name = "dgvtxtBatchId";
            dgvtxtBatchId.ReadOnly = true;
            dgvtxtBatchId.SortMode = DataGridViewColumnSortMode.NotSortable;
            dgvtxtBatchId.Visible = false;
            dgvtxtBatchno.DataPropertyName = "batchNo";
            dgvtxtBatchno.HeaderText = "Batch";
            dgvtxtBatchno.Name = "dgvtxtBatchno";
            dgvtxtBatchno.ReadOnly = true;
            dgvtxtBatchno.SortMode = DataGridViewColumnSortMode.NotSortable;
            dgvtxtBatchno.Visible = false;
            dgvtxtRackId.DataPropertyName = "rackId";
            dgvtxtRackId.HeaderText = "rackId";
            dgvtxtRackId.Name = "dgvtxtRackId";
            dgvtxtRackId.ReadOnly = true;
            dgvtxtRackId.SortMode = DataGridViewColumnSortMode.NotSortable;
            dgvtxtRackId.Visible = false;
            dgvtxtRackName.DataPropertyName = "rackName";
            dgvtxtRackName.HeaderText = "Rack";
            dgvtxtRackName.Name = "dgvtxtRackName";
            dgvtxtRackName.ReadOnly = true;
            dgvtxtRackName.SortMode = DataGridViewColumnSortMode.NotSortable;
            dgvtxtRackName.Visible = false;
            dgvtxtGodownId.DataPropertyName = "godownId";
            dgvtxtGodownId.HeaderText = "godownId";
            dgvtxtGodownId.Name = "dgvtxtGodownId";
            dgvtxtGodownId.ReadOnly = true;
            dgvtxtGodownId.SortMode = DataGridViewColumnSortMode.NotSortable;
            dgvtxtGodownId.Visible = false;
            dgvtxtGodownName.DataPropertyName = "godownName";
            dgvtxtGodownName.HeaderText = "Godown";
            dgvtxtGodownName.Name = "dgvtxtGodownName";
            dgvtxtGodownName.ReadOnly = true;
            dgvtxtGodownName.SortMode = DataGridViewColumnSortMode.NotSortable;
            dgvtxtGodownName.Visible = false;
            dgvtxtUnitId.DataPropertyName = "unitId";
            dgvtxtUnitId.HeaderText = "UnitId";
            dgvtxtUnitId.Name = "dgvtxtUnitId";
            dgvtxtUnitId.ReadOnly = true;
            dgvtxtUnitId.SortMode = DataGridViewColumnSortMode.NotSortable;
            dgvtxtUnitId.Visible = false;
            dgvtxtunitconversionId.DataPropertyName = "unitconversionId";
            dgvtxtunitconversionId.HeaderText = "unitconversionId";
            dgvtxtunitconversionId.Name = "dgvtxtunitconversionId";
            dgvtxtunitconversionId.ReadOnly = true;
            dgvtxtunitconversionId.SortMode = DataGridViewColumnSortMode.NotSortable;
            dgvtxtunitconversionId.Visible = false;
            dgvtxtBarcode.HeaderText = "Barcode";
            dgvtxtBarcode.Name = "dgvtxtBarcode";
            dgvtxtBarcode.ReadOnly = true;
            dgvtxtBarcode.SortMode = DataGridViewColumnSortMode.NotSortable;
            dgvtxtBarcode.Visible = false;
            dgvtxtDiscountPercentage.HeaderText = "DiscountPercentage";
            dgvtxtDiscountPercentage.Name = "dgvtxtDiscountPercentage";
            dgvtxtDiscountPercentage.ReadOnly = true;
            dgvtxtDiscountPercentage.SortMode = DataGridViewColumnSortMode.NotSortable;
            dgvtxtDiscountPercentage.Visible = false;
            dgvtxtSalesDetailsId.HeaderText = "salesDetailsId";
            dgvtxtSalesDetailsId.Name = "dgvtxtSalesDetailsId";
            dgvtxtSalesDetailsId.ReadOnly = true;
            dgvtxtSalesDetailsId.SortMode = DataGridViewColumnSortMode.NotSortable;
            dgvtxtSalesDetailsId.Visible = false;
            lblDate.AutoSize = true;
            lblDate.BackColor = Color.Transparent;
            lblDate.ForeColor = Color.Black;
            lblDate.Location = new Point(284, 18);
            lblDate.Margin = new Padding(5);
            lblDate.Name = "lblDate";
            lblDate.Size = new Size(30, 13);
            lblDate.TabIndex = 1122;
            lblDate.Text = "Date";
            cmbSalesMan.DropDownStyle = ComboBoxStyle.DropDownList;
            cmbSalesMan.FormattingEnabled = true;
            cmbSalesMan.Location = new Point(775, 14);
            cmbSalesMan.Margin = new Padding(5);
            cmbSalesMan.Name = "cmbSalesMan";
            cmbSalesMan.Size = new Size(170, 21);
            cmbSalesMan.TabIndex = 3;
            cmbSalesMan.KeyDown += cmbSalesMan_KeyDown;
            lblSalesMan.AutoSize = true;
            lblSalesMan.BackColor = Color.Transparent;
            lblSalesMan.ForeColor = Color.Black;
            lblSalesMan.Location = new Point(717, 18);
            lblSalesMan.Margin = new Padding(5);
            lblSalesMan.Name = "lblSalesMan";
            lblSalesMan.Size = new Size(53, 13);
            lblSalesMan.TabIndex = 1124;
            lblSalesMan.Text = "Salesman";
            btnNewLedger.BackColor = Color.Gray;
            btnNewLedger.BackgroundImageLayout = ImageLayout.None;
            btnNewLedger.FlatAppearance.BorderSize = 0;
            btnNewLedger.FlatStyle = FlatStyle.Flat;
            btnNewLedger.Font = new Font("Bauhaus 93", 8.25f, FontStyle.Regular, GraphicsUnit.Point, 0);
            btnNewLedger.ForeColor = Color.White;
            btnNewLedger.Location = new Point(376, 40);
            btnNewLedger.Name = "btnNewLedger";
            btnNewLedger.Size = new Size(21, 20);
            btnNewLedger.TabIndex = 6;
            btnNewLedger.Text = "+";
            btnNewLedger.UseVisualStyleBackColor = false;
            btnNewLedger.Click += btnNewLedger_Click;
            btnNewSalesAccount.BackColor = Color.Gray;
            btnNewSalesAccount.BackgroundImageLayout = ImageLayout.None;
            btnNewSalesAccount.FlatAppearance.BorderSize = 0;
            btnNewSalesAccount.FlatStyle = FlatStyle.Flat;
            btnNewSalesAccount.Font = new Font("Bauhaus 93", 8.25f, FontStyle.Regular, GraphicsUnit.Point, 0);
            btnNewSalesAccount.ForeColor = Color.White;
            btnNewSalesAccount.Location = new Point(677, 39);
            btnNewSalesAccount.Name = "btnNewSalesAccount";
            btnNewSalesAccount.Size = new Size(21, 20);
            btnNewSalesAccount.TabIndex = 8;
            btnNewSalesAccount.Text = "+";
            btnNewSalesAccount.UseVisualStyleBackColor = false;
            btnNewSalesAccount.Click += btnNewSalesAccount_Click;
            cmbSalesAccount.DropDownStyle = ComboBoxStyle.DropDownList;
            cmbSalesAccount.FormattingEnabled = true;
            cmbSalesAccount.Location = new Point(505, 39);
            cmbSalesAccount.Margin = new Padding(5);
            cmbSalesAccount.Name = "cmbSalesAccount";
            cmbSalesAccount.Size = new Size(168, 21);
            cmbSalesAccount.TabIndex = 7;
            cmbSalesAccount.KeyDown += cmbSalesAccount_KeyDown;
            lblsalesAccount.AutoSize = true;
            lblsalesAccount.BackColor = Color.Transparent;
            lblsalesAccount.ForeColor = Color.Black;
            lblsalesAccount.Location = new Point(417, 43);
            lblsalesAccount.Margin = new Padding(5);
            lblsalesAccount.Name = "lblsalesAccount";
            lblsalesAccount.Size = new Size(54, 13);
            lblsalesAccount.TabIndex = 1127;
            lblsalesAccount.Text = "Sales A/c";
            btnNewCounter.BackColor = Color.Gray;
            btnNewCounter.BackgroundImageLayout = ImageLayout.None;
            btnNewCounter.FlatAppearance.BorderSize = 0;
            btnNewCounter.FlatStyle = FlatStyle.Flat;
            btnNewCounter.Font = new Font("Bauhaus 93", 8.25f, FontStyle.Regular, GraphicsUnit.Point, 0);
            btnNewCounter.ForeColor = Color.White;
            btnNewCounter.Location = new Point(953, 39);
            btnNewCounter.Name = "btnNewCounter";
            btnNewCounter.Size = new Size(21, 20);
            btnNewCounter.TabIndex = 10;
            btnNewCounter.Text = "+";
            btnNewCounter.UseVisualStyleBackColor = false;
            btnNewCounter.Click += btnNewCounter_Click;
            cmbCounter.DropDownStyle = ComboBoxStyle.DropDownList;
            cmbCounter.FormattingEnabled = true;
            cmbCounter.Location = new Point(775, 39);
            cmbCounter.Margin = new Padding(5);
            cmbCounter.Name = "cmbCounter";
            cmbCounter.Size = new Size(170, 21);
            cmbCounter.TabIndex = 9;
            cmbCounter.KeyDown += cmbCounter_KeyDown;
            lblCounter.AutoSize = true;
            lblCounter.BackColor = Color.Transparent;
            lblCounter.ForeColor = Color.Black;
            lblCounter.Location = new Point(718, 43);
            lblCounter.Margin = new Padding(5);
            lblCounter.Name = "lblCounter";
            lblCounter.Size = new Size(44, 13);
            lblCounter.TabIndex = 1130;
            lblCounter.Text = "Counter";
            gbxDetails.Controls.Add(groupBox1);
            gbxDetails.Controls.Add(lblUnitConversion);
            gbxDetails.Controls.Add(lblUnitConversionRate);
            gbxDetails.Controls.Add(lblUnitConversionId);
            gbxDetails.Controls.Add(btnAdd);
            gbxDetails.Controls.Add(txtAmount);
            gbxDetails.Controls.Add(lblAmount);
            gbxDetails.Controls.Add(txtDiscountAmount);
            gbxDetails.Controls.Add(lblDiscountAmt);
            gbxDetails.Controls.Add(txtDiscountPercentage);
            gbxDetails.Controls.Add(lblDiscountPercentage);
            gbxDetails.Controls.Add(txtNetAmount);
            gbxDetails.Controls.Add(lblnetAmount);
            gbxDetails.Controls.Add(txtTaxAmount);
            gbxDetails.Controls.Add(lblTaxAmount);
            gbxDetails.Controls.Add(cmbTax);
            gbxDetails.Controls.Add(lblTax);
            gbxDetails.Controls.Add(txtGrossValue);
            gbxDetails.Controls.Add(lblGrossValue);
            gbxDetails.Controls.Add(txtRate);
            gbxDetails.Controls.Add(lblRate);
            gbxDetails.Controls.Add(cmbUnit);
            gbxDetails.Controls.Add(lblUnit);
            gbxDetails.Controls.Add(txtQuantity);
            gbxDetails.Controls.Add(lblQuantity);
            gbxDetails.Controls.Add(cmbBatch);
            gbxDetails.Controls.Add(lblBatch);
            gbxDetails.Controls.Add(cmbRack);
            gbxDetails.Controls.Add(lblRack);
            gbxDetails.Controls.Add(cmbGodown);
            gbxDetails.Controls.Add(lblGodown);
            gbxDetails.Controls.Add(cmbItem);
            gbxDetails.Controls.Add(lblItem);
            gbxDetails.Controls.Add(txtProductCode);
            gbxDetails.Controls.Add(lblProductcode);
            gbxDetails.Controls.Add(txtBarcode);
            gbxDetails.Controls.Add(lblBarcode);
            gbxDetails.Font = new Font("Arial", 9f, FontStyle.Bold, GraphicsUnit.Point, 0);
            gbxDetails.ForeColor = Color.Maroon;
            gbxDetails.Location = new Point(18, 70);
            gbxDetails.Name = "gbxDetails";
            gbxDetails.Size = new Size(956, 176);
            gbxDetails.TabIndex = 11;
            gbxDetails.TabStop = false;
            gbxDetails.Text = "Details";
            groupBox1.BackColor = Color.Black;
            groupBox1.ForeColor = Color.Black;
            groupBox1.Location = new Point(9, 17);
            groupBox1.Name = "groupBox1";
            groupBox1.Size = new Size(70, 1);
            groupBox1.TabIndex = 1179;
            groupBox1.TabStop = false;
            lblUnitConversion.AutoSize = true;
            lblUnitConversion.Location = new Point(385, 144);
            lblUnitConversion.Name = "lblUnitConversion";
            lblUnitConversion.Size = new Size(0, 15);
            lblUnitConversion.TabIndex = 17;
            lblUnitConversion.Visible = false;
            lblUnitConversionRate.AutoSize = true;
            lblUnitConversionRate.Location = new Point(334, 144);
            lblUnitConversionRate.Name = "lblUnitConversionRate";
            lblUnitConversionRate.Size = new Size(0, 15);
            lblUnitConversionRate.TabIndex = 16;
            lblUnitConversionRate.Visible = false;
            lblUnitConversionId.AutoSize = true;
            lblUnitConversionId.Location = new Point(334, 144);
            lblUnitConversionId.Name = "lblUnitConversionId";
            lblUnitConversionId.Size = new Size(0, 15);
            lblUnitConversionId.TabIndex = 1161;
            btnAdd.BackColor = Color.LightSteelBlue;
            btnAdd.FlatAppearance.BorderSize = 0;
            btnAdd.FlatStyle = FlatStyle.Flat;
            btnAdd.Font = new Font("Microsoft Sans Serif", 8.25f, FontStyle.Regular, GraphicsUnit.Point, 0);
            btnAdd.ForeColor = Color.Black;
            btnAdd.Location = new Point(842, 141);
            btnAdd.Name = "btnAdd";
            btnAdd.Size = new Size(85, 27);
            btnAdd.TabIndex = 16;
            btnAdd.Text = "Add";
            btnAdd.UseVisualStyleBackColor = false;
            btnAdd.Click += btnAdd_Click;
            btnAdd.KeyDown += btnAdd_KeyDown;
            txtAmount.BackColor = Color.White;
            txtAmount.Font = new Font("Microsoft Sans Serif", 8.25f, FontStyle.Regular, GraphicsUnit.Point, 0);
            txtAmount.ForeColor = Color.Black;
            txtAmount.Location = new Point(562, 118);
            txtAmount.Margin = new Padding(5, 5, 5, 0);
            txtAmount.Name = "txtAmount";
            txtAmount.ReadOnly = true;
            txtAmount.Size = new Size(365, 20);
            txtAmount.TabIndex = 15;
            txtAmount.TextAlign = HorizontalAlignment.Right;
            lblAmount.AutoSize = true;
            lblAmount.BackColor = Color.Transparent;
            lblAmount.Font = new Font("Microsoft Sans Serif", 8.25f, FontStyle.Regular, GraphicsUnit.Point, 0);
            lblAmount.ForeColor = Color.Black;
            lblAmount.Location = new Point(485, 122);
            lblAmount.Margin = new Padding(5);
            lblAmount.Name = "lblAmount";
            lblAmount.Size = new Size(43, 13);
            lblAmount.TabIndex = 1159;
            lblAmount.Text = "Amount";
            txtDiscountAmount.Font = new Font("Microsoft Sans Serif", 8.25f, FontStyle.Regular, GraphicsUnit.Point, 0);
            txtDiscountAmount.ForeColor = Color.Black;
            txtDiscountAmount.Location = new Point(334, 94);
            txtDiscountAmount.Margin = new Padding(5, 5, 5, 0);
            txtDiscountAmount.MaxLength = 8;
            txtDiscountAmount.Name = "txtDiscountAmount";
            txtDiscountAmount.Size = new Size(125, 20);
            txtDiscountAmount.TabIndex = 11;
            txtDiscountAmount.Text = "0";
            txtDiscountAmount.TextAlign = HorizontalAlignment.Right;
            txtDiscountAmount.TextChanged += txtDiscountAmount_TextChanged;
            txtDiscountAmount.KeyDown += txtDiscountAmount_KeyDown;
            txtDiscountAmount.KeyPress += txtDiscountAmount_KeyPress;
            txtDiscountAmount.Leave += txtDiscountAmount_Leave;
            lblDiscountAmt.AutoSize = true;
            lblDiscountAmt.BackColor = Color.Transparent;
            lblDiscountAmt.Font = new Font("Microsoft Sans Serif", 8.25f, FontStyle.Regular, GraphicsUnit.Point, 0);
            lblDiscountAmt.ForeColor = Color.Black;
            lblDiscountAmt.Location = new Point(257, 102);
            lblDiscountAmt.Margin = new Padding(5);
            lblDiscountAmt.Name = "lblDiscountAmt";
            lblDiscountAmt.Size = new Size(73, 13);
            lblDiscountAmt.TabIndex = 1157;
            lblDiscountAmt.Text = "Discount Amt.";
            txtDiscountPercentage.Font = new Font("Microsoft Sans Serif", 8.25f, FontStyle.Regular, GraphicsUnit.Point, 0);
            txtDiscountPercentage.ForeColor = Color.Black;
            txtDiscountPercentage.Location = new Point(101, 95);
            txtDiscountPercentage.Margin = new Padding(5, 5, 5, 0);
            txtDiscountPercentage.MaxLength = 6;
            txtDiscountPercentage.Name = "txtDiscountPercentage";
            txtDiscountPercentage.Size = new Size(125, 20);
            txtDiscountPercentage.TabIndex = 10;
            txtDiscountPercentage.TextAlign = HorizontalAlignment.Right;
            txtDiscountPercentage.TextChanged += txtDiscountPercentage_TextChanged;
            txtDiscountPercentage.KeyDown += txtDiscountPercentage_KeyDown;
            txtDiscountPercentage.KeyPress += txtDiscountPercentage_KeyPress;
            txtDiscountPercentage.Leave += txtDiscountPercentage_Leave;
            lblDiscountPercentage.AutoSize = true;
            lblDiscountPercentage.BackColor = Color.Transparent;
            lblDiscountPercentage.Font = new Font("Microsoft Sans Serif", 8.25f, FontStyle.Regular, GraphicsUnit.Point, 0);
            lblDiscountPercentage.ForeColor = Color.Black;
            lblDiscountPercentage.Location = new Point(24, 103);
            lblDiscountPercentage.Margin = new Padding(5);
            lblDiscountPercentage.Name = "lblDiscountPercentage";
            lblDiscountPercentage.Size = new Size(60, 13);
            lblDiscountPercentage.TabIndex = 1155;
            lblDiscountPercentage.Text = "Discount %";
            txtNetAmount.BackColor = Color.White;
            txtNetAmount.Font = new Font("Microsoft Sans Serif", 8.25f, FontStyle.Regular, GraphicsUnit.Point, 0);
            txtNetAmount.ForeColor = Color.Black;
            txtNetAmount.Location = new Point(562, 93);
            txtNetAmount.Margin = new Padding(5, 5, 5, 0);
            txtNetAmount.Name = "txtNetAmount";
            txtNetAmount.ReadOnly = true;
            txtNetAmount.Size = new Size(365, 20);
            txtNetAmount.TabIndex = 12;
            txtNetAmount.TextAlign = HorizontalAlignment.Right;
            txtNetAmount.TextChanged += txtNetAmount_TextChanged;
            lblnetAmount.AutoSize = true;
            lblnetAmount.BackColor = Color.Transparent;
            lblnetAmount.Font = new Font("Microsoft Sans Serif", 8.25f, FontStyle.Regular, GraphicsUnit.Point, 0);
            lblnetAmount.ForeColor = Color.Black;
            lblnetAmount.Location = new Point(485, 97);
            lblnetAmount.Margin = new Padding(5);
            lblnetAmount.Name = "lblnetAmount";
            lblnetAmount.Size = new Size(63, 13);
            lblnetAmount.TabIndex = 1153;
            lblnetAmount.Text = "Net Amount";
            txtTaxAmount.BackColor = Color.White;
            txtTaxAmount.Font = new Font("Microsoft Sans Serif", 8.25f, FontStyle.Regular, GraphicsUnit.Point, 0);
            txtTaxAmount.ForeColor = Color.Black;
            txtTaxAmount.Location = new Point(334, 120);
            txtTaxAmount.Margin = new Padding(5, 5, 5, 0);
            txtTaxAmount.Name = "txtTaxAmount";
            txtTaxAmount.ReadOnly = true;
            txtTaxAmount.Size = new Size(125, 20);
            txtTaxAmount.TabIndex = 14;
            txtTaxAmount.TextAlign = HorizontalAlignment.Right;
            lblTaxAmount.AutoSize = true;
            lblTaxAmount.BackColor = Color.Transparent;
            lblTaxAmount.Font = new Font("Microsoft Sans Serif", 8.25f, FontStyle.Regular, GraphicsUnit.Point, 0);
            lblTaxAmount.ForeColor = Color.Black;
            lblTaxAmount.Location = new Point(257, 124);
            lblTaxAmount.Margin = new Padding(5);
            lblTaxAmount.Name = "lblTaxAmount";
            lblTaxAmount.Size = new Size(64, 13);
            lblTaxAmount.TabIndex = 1151;
            lblTaxAmount.Text = "Tax Amount";
            cmbTax.BackColor = Color.White;
            cmbTax.DropDownStyle = ComboBoxStyle.DropDownList;
            cmbTax.Enabled = false;
            cmbTax.Font = new Font("Microsoft Sans Serif", 8.25f, FontStyle.Regular, GraphicsUnit.Point, 0);
            cmbTax.ForeColor = Color.Black;
            cmbTax.FormattingEnabled = true;
            cmbTax.Location = new Point(101, 120);
            cmbTax.Margin = new Padding(5, 5, 5, 0);
            cmbTax.Name = "cmbTax";
            cmbTax.Size = new Size(125, 21);
            cmbTax.TabIndex = 13;
            cmbTax.KeyDown += cmbTax_KeyDown;
            lblTax.AutoSize = true;
            lblTax.BackColor = Color.Transparent;
            lblTax.Font = new Font("Microsoft Sans Serif", 8.25f, FontStyle.Regular, GraphicsUnit.Point, 0);
            lblTax.ForeColor = Color.Black;
            lblTax.Location = new Point(24, 124);
            lblTax.Margin = new Padding(5);
            lblTax.Name = "lblTax";
            lblTax.Size = new Size(25, 13);
            lblTax.TabIndex = 1149;
            lblTax.Text = "Tax";
            txtGrossValue.BackColor = Color.White;
            txtGrossValue.Font = new Font("Microsoft Sans Serif", 8.25f, FontStyle.Regular, GraphicsUnit.Point, 0);
            txtGrossValue.ForeColor = Color.Black;
            txtGrossValue.Location = new Point(802, 68);
            txtGrossValue.Margin = new Padding(5, 5, 5, 0);
            txtGrossValue.Name = "txtGrossValue";
            txtGrossValue.ReadOnly = true;
            txtGrossValue.Size = new Size(125, 20);
            txtGrossValue.TabIndex = 9;
            txtGrossValue.TextAlign = HorizontalAlignment.Right;
            txtGrossValue.TextChanged += txtGrossValue_TextChanged;
            lblGrossValue.AutoSize = true;
            lblGrossValue.Font = new Font("Microsoft Sans Serif", 8.25f, FontStyle.Regular, GraphicsUnit.Point, 0);
            lblGrossValue.ForeColor = Color.Black;
            lblGrossValue.Location = new Point(725, 72);
            lblGrossValue.Margin = new Padding(5);
            lblGrossValue.Name = "lblGrossValue";
            lblGrossValue.Size = new Size(64, 13);
            lblGrossValue.TabIndex = 1147;
            lblGrossValue.Text = "Gross Value";
            txtRate.Font = new Font("Microsoft Sans Serif", 8.25f, FontStyle.Regular, GraphicsUnit.Point, 0);
            txtRate.ForeColor = Color.Black;
            txtRate.Location = new Point(562, 68);
            txtRate.Margin = new Padding(5, 5, 5, 0);
            txtRate.MaxLength = 9;
            txtRate.Name = "txtRate";
            txtRate.Size = new Size(125, 20);
            txtRate.TabIndex = 8;
            txtRate.Text = "0";
            txtRate.TextAlign = HorizontalAlignment.Right;
            txtRate.TextChanged += txtRate_TextChanged;
            txtRate.KeyDown += txtRate_KeyDown;
            txtRate.KeyPress += txtRate_KeyPress;
            lblRate.AutoSize = true;
            lblRate.BackColor = Color.Transparent;
            lblRate.Font = new Font("Microsoft Sans Serif", 8.25f, FontStyle.Regular, GraphicsUnit.Point, 0);
            lblRate.ForeColor = Color.Black;
            lblRate.Location = new Point(485, 72);
            lblRate.Margin = new Padding(5);
            lblRate.Name = "lblRate";
            lblRate.Size = new Size(30, 13);
            lblRate.TabIndex = 1145;
            lblRate.Text = "Rate";
            cmbUnit.DropDownStyle = ComboBoxStyle.DropDownList;
            cmbUnit.Font = new Font("Microsoft Sans Serif", 8.25f, FontStyle.Regular, GraphicsUnit.Point, 0);
            cmbUnit.ForeColor = Color.Black;
            cmbUnit.FormattingEnabled = true;
            cmbUnit.Location = new Point(334, 68);
            cmbUnit.Margin = new Padding(5, 5, 5, 0);
            cmbUnit.Name = "cmbUnit";
            cmbUnit.Size = new Size(125, 21);
            cmbUnit.TabIndex = 7;
            cmbUnit.SelectedValueChanged += cmbUnit_SelectedValueChanged;
            cmbUnit.Enter += cmbUnit_Enter;
            cmbUnit.KeyDown += cmbUnit_KeyDown;
            lblUnit.AutoSize = true;
            lblUnit.BackColor = Color.Transparent;
            lblUnit.Font = new Font("Microsoft Sans Serif", 8.25f, FontStyle.Regular, GraphicsUnit.Point, 0);
            lblUnit.ForeColor = Color.Black;
            lblUnit.Location = new Point(257, 72);
            lblUnit.Margin = new Padding(5);
            lblUnit.Name = "lblUnit";
            lblUnit.Size = new Size(26, 13);
            lblUnit.TabIndex = 1143;
            lblUnit.Text = "Unit";
            txtQuantity.Font = new Font("Microsoft Sans Serif", 8.25f, FontStyle.Regular, GraphicsUnit.Point, 0);
            txtQuantity.ForeColor = Color.Black;
            txtQuantity.Location = new Point(101, 68);
            txtQuantity.Margin = new Padding(5, 5, 5, 0);
            txtQuantity.MaxLength = 9;
            txtQuantity.Name = "txtQuantity";
            txtQuantity.Size = new Size(125, 20);
            txtQuantity.TabIndex = 6;
            txtQuantity.Text = "0";
            txtQuantity.TextAlign = HorizontalAlignment.Right;
            txtQuantity.TextChanged += txtQuantity_TextChanged;
            txtQuantity.KeyDown += txtQuantity_KeyDown;
            txtQuantity.KeyPress += txtQuantity_KeyPress;
            lblQuantity.AutoSize = true;
            lblQuantity.BackColor = Color.Transparent;
            lblQuantity.Font = new Font("Microsoft Sans Serif", 8.25f, FontStyle.Regular, GraphicsUnit.Point, 0);
            lblQuantity.ForeColor = Color.Black;
            lblQuantity.Location = new Point(24, 72);
            lblQuantity.Margin = new Padding(5);
            lblQuantity.Name = "lblQuantity";
            lblQuantity.Size = new Size(26, 13);
            lblQuantity.TabIndex = 1141;
            lblQuantity.Text = "Qty.";
            cmbBatch.DropDownStyle = ComboBoxStyle.DropDownList;
            cmbBatch.Font = new Font("Microsoft Sans Serif", 8.25f, FontStyle.Regular, GraphicsUnit.Point, 0);
            cmbBatch.ForeColor = Color.Black;
            cmbBatch.FormattingEnabled = true;
            cmbBatch.Location = new Point(562, 42);
            cmbBatch.Margin = new Padding(5);
            cmbBatch.Name = "cmbBatch";
            cmbBatch.Size = new Size(365, 21);
            cmbBatch.TabIndex = 5;
            cmbBatch.KeyDown += cmbBatch_KeyDown;
            lblBatch.AutoSize = true;
            lblBatch.BackColor = Color.Transparent;
            lblBatch.Font = new Font("Microsoft Sans Serif", 8.25f, FontStyle.Regular, GraphicsUnit.Point, 0);
            lblBatch.ForeColor = Color.Black;
            lblBatch.Location = new Point(485, 46);
            lblBatch.Margin = new Padding(5);
            lblBatch.Name = "lblBatch";
            lblBatch.Size = new Size(35, 13);
            lblBatch.TabIndex = 1139;
            lblBatch.Text = "Batch";
            cmbRack.DropDownStyle = ComboBoxStyle.DropDownList;
            cmbRack.Font = new Font("Microsoft Sans Serif", 8.25f, FontStyle.Regular, GraphicsUnit.Point, 0);
            cmbRack.ForeColor = Color.Black;
            cmbRack.FormattingEnabled = true;
            cmbRack.Location = new Point(334, 42);
            cmbRack.Margin = new Padding(5, 5, 5, 0);
            cmbRack.Name = "cmbRack";
            cmbRack.Size = new Size(125, 21);
            cmbRack.TabIndex = 4;
            cmbRack.KeyDown += cmbRack_KeyDown;
            lblRack.AutoSize = true;
            lblRack.BackColor = Color.Transparent;
            lblRack.Font = new Font("Microsoft Sans Serif", 8.25f, FontStyle.Regular, GraphicsUnit.Point, 0);
            lblRack.ForeColor = Color.Black;
            lblRack.Location = new Point(257, 46);
            lblRack.Margin = new Padding(5);
            lblRack.Name = "lblRack";
            lblRack.Size = new Size(33, 13);
            lblRack.TabIndex = 1137;
            lblRack.Text = "Rack";
            cmbGodown.DropDownStyle = ComboBoxStyle.DropDownList;
            cmbGodown.Font = new Font("Microsoft Sans Serif", 8.25f, FontStyle.Regular, GraphicsUnit.Point, 0);
            cmbGodown.ForeColor = Color.Black;
            cmbGodown.FormattingEnabled = true;
            cmbGodown.Location = new Point(101, 42);
            cmbGodown.Margin = new Padding(5, 5, 5, 0);
            cmbGodown.Name = "cmbGodown";
            cmbGodown.Size = new Size(125, 21);
            cmbGodown.TabIndex = 3;
            cmbGodown.SelectedIndexChanged += cmbGodown_SelectedIndexChanged;
            cmbGodown.KeyDown += cmbGodown_KeyDown;
            lblGodown.AutoSize = true;
            lblGodown.BackColor = Color.Transparent;
            lblGodown.Font = new Font("Microsoft Sans Serif", 8.25f, FontStyle.Regular, GraphicsUnit.Point, 0);
            lblGodown.ForeColor = Color.Black;
            lblGodown.Location = new Point(24, 46);
            lblGodown.Margin = new Padding(5);
            lblGodown.Name = "lblGodown";
            lblGodown.Size = new Size(47, 13);
            lblGodown.TabIndex = 1135;
            lblGodown.Text = "Godown";
            cmbItem.DropDownStyle = ComboBoxStyle.DropDownList;
            cmbItem.Font = new Font("Microsoft Sans Serif", 8.25f, FontStyle.Regular, GraphicsUnit.Point, 0);
            cmbItem.ForeColor = Color.Black;
            cmbItem.FormattingEnabled = true;
            cmbItem.Location = new Point(562, 17);
            cmbItem.Margin = new Padding(5);
            cmbItem.Name = "cmbItem";
            cmbItem.Size = new Size(365, 21);
            cmbItem.TabIndex = 2;
            cmbItem.SelectedIndexChanged += cmbItem_SelectedIndexChanged;
            cmbItem.KeyDown += cmbItem_KeyDown;
            lblItem.AutoSize = true;
            lblItem.BackColor = Color.Transparent;
            lblItem.Font = new Font("Microsoft Sans Serif", 8.25f, FontStyle.Regular, GraphicsUnit.Point, 0);
            lblItem.ForeColor = Color.Black;
            lblItem.Location = new Point(485, 21);
            lblItem.Margin = new Padding(5);
            lblItem.Name = "lblItem";
            lblItem.Size = new Size(27, 13);
            lblItem.TabIndex = 1125;
            lblItem.Text = "Item";
            txtProductCode.Font = new Font("Microsoft Sans Serif", 8.25f, FontStyle.Regular, GraphicsUnit.Point, 0);
            txtProductCode.ForeColor = Color.Black;
            txtProductCode.Location = new Point(334, 17);
            txtProductCode.Margin = new Padding(5, 5, 5, 0);
            txtProductCode.Name = "txtProductCode";
            txtProductCode.Size = new Size(125, 20);
            txtProductCode.TabIndex = 1;
            txtProductCode.KeyDown += txtProductCode_KeyDown;
            txtProductCode.Leave += txtProductCode_Leave;
            lblProductcode.AutoSize = true;
            lblProductcode.BackColor = Color.Transparent;
            lblProductcode.Font = new Font("Microsoft Sans Serif", 8.25f, FontStyle.Regular, GraphicsUnit.Point, 0);
            lblProductcode.ForeColor = Color.Black;
            lblProductcode.Location = new Point(257, 21);
            lblProductcode.Margin = new Padding(5);
            lblProductcode.Name = "lblProductcode";
            lblProductcode.Size = new Size(72, 13);
            lblProductcode.TabIndex = 1123;
            lblProductcode.Text = "Product Code";
            txtBarcode.Font = new Font("Microsoft Sans Serif", 8.25f, FontStyle.Regular, GraphicsUnit.Point, 0);
            txtBarcode.ForeColor = Color.Black;
            txtBarcode.Location = new Point(101, 17);
            txtBarcode.Margin = new Padding(5, 5, 5, 0);
            txtBarcode.Name = "txtBarcode";
            txtBarcode.Size = new Size(125, 20);
            txtBarcode.TabIndex = 0;
            txtBarcode.KeyDown += txtBarcode_KeyDown;
            txtBarcode.Leave += txtBarcode_Leave;
            lblBarcode.AutoSize = true;
            lblBarcode.BackColor = Color.Transparent;
            lblBarcode.Font = new Font("Microsoft Sans Serif", 8.25f, FontStyle.Regular, GraphicsUnit.Point, 0);
            lblBarcode.ForeColor = Color.Black;
            lblBarcode.Location = new Point(24, 21);
            lblBarcode.Margin = new Padding(5);
            lblBarcode.Name = "lblBarcode";
            lblBarcode.Size = new Size(47, 13);
            lblBarcode.TabIndex = 1121;
            lblBarcode.Text = "Barcode";
            lnklblRemove.ActiveLinkColor = Color.Brown;
            lnklblRemove.AutoSize = true;
            lnklblRemove.LinkColor = Color.Brown;
            lnklblRemove.Location = new Point(927, 417);
            lnklblRemove.Name = "lnklblRemove";
            lnklblRemove.Size = new Size(47, 13);
            lnklblRemove.TabIndex = 18;
            lnklblRemove.TabStop = true;
            lnklblRemove.Text = "Remove";
            lnklblRemove.VisitedLinkColor = Color.Brown;
            lnklblRemove.LinkClicked += lnklblRemove_LinkClicked;
            txtTotalAmount.BackColor = Color.White;
            txtTotalAmount.Location = new Point(849, 451);
            txtTotalAmount.Margin = new Padding(5, 5, 5, 0);
            txtTotalAmount.Name = "txtTotalAmount";
            txtTotalAmount.ReadOnly = true;
            txtTotalAmount.Size = new Size(125, 20);
            txtTotalAmount.TabIndex = 1160;
            txtTotalAmount.TextAlign = HorizontalAlignment.Right;
            lblTotal.AutoSize = true;
            lblTotal.ForeColor = Color.Black;
            lblTotal.Location = new Point(777, 455);
            lblTotal.Margin = new Padding(5);
            lblTotal.Name = "lblTotal";
            lblTotal.Size = new Size(31, 13);
            lblTotal.TabIndex = 1159;
            lblTotal.Text = "Total";
            txtBillDiscount.Location = new Point(849, 476);
            txtBillDiscount.Margin = new Padding(5, 5, 5, 0);
            txtBillDiscount.MaxLength = 10;
            txtBillDiscount.Name = "txtBillDiscount";
            txtBillDiscount.Size = new Size(125, 20);
            txtBillDiscount.TabIndex = 16;
            txtBillDiscount.TextAlign = HorizontalAlignment.Right;
            txtBillDiscount.TextChanged += txtBillDiscount_TextChanged;
            txtBillDiscount.Enter += txtBillDiscount_Enter;
            txtBillDiscount.KeyDown += txtBillDiscount_KeyDown;
            txtBillDiscount.KeyPress += txtBillDiscount_KeyPress;
            txtBillDiscount.Leave += txtBillDiscount_Leave;
            lblDiscount.AutoSize = true;
            lblDiscount.ForeColor = Color.Black;
            lblDiscount.Location = new Point(777, 480);
            lblDiscount.Margin = new Padding(5);
            lblDiscount.Name = "lblDiscount";
            lblDiscount.Size = new Size(49, 13);
            lblDiscount.TabIndex = 1161;
            lblDiscount.Text = "Discount";
            txtGrandTotal.BackColor = Color.White;
            txtGrandTotal.Location = new Point(849, 501);
            txtGrandTotal.Margin = new Padding(5, 5, 5, 0);
            txtGrandTotal.Name = "txtGrandTotal";
            txtGrandTotal.ReadOnly = true;
            txtGrandTotal.Size = new Size(125, 20);
            txtGrandTotal.TabIndex = 1164;
            txtGrandTotal.TextAlign = HorizontalAlignment.Right;
            txtGrandTotal.TextChanged += txtGrandTotal_TextChanged;
            lblGrandTotal.AutoSize = true;
            lblGrandTotal.ForeColor = Color.Black;
            lblGrandTotal.Location = new Point(777, 505);
            lblGrandTotal.Margin = new Padding(5);
            lblGrandTotal.Name = "lblGrandTotal";
            lblGrandTotal.Size = new Size(63, 13);
            lblGrandTotal.TabIndex = 1163;
            lblGrandTotal.Text = "Grand Total";
            dgvPOSTax.AllowUserToAddRows = false;
            dgvPOSTax.AllowUserToDeleteRows = false;
            dgvPOSTax.AllowUserToResizeColumns = false;
            dgvPOSTax.AllowUserToResizeRows = false;
            dgvPOSTax.AutoSizeColumnsMode = DataGridViewAutoSizeColumnsMode.Fill;
            dgvPOSTax.BackgroundColor = Color.White;
            dgvPOSTax.ColumnHeadersBorderStyle = DataGridViewHeaderBorderStyle.Single;
            dataGridViewCellStyle19.Alignment = DataGridViewContentAlignment.MiddleLeft;
            dataGridViewCellStyle19.BackColor = Color.DimGray;
            dataGridViewCellStyle19.Font = new Font("Arial", 9f, FontStyle.Bold, GraphicsUnit.Point, 0);
            dataGridViewCellStyle19.ForeColor = Color.White;
            dataGridViewCellStyle19.SelectionBackColor = Color.Silver;
            dataGridViewCellStyle19.SelectionForeColor = Color.White;
            dataGridViewCellStyle19.WrapMode = DataGridViewTriState.True;
            dgvPOSTax.ColumnHeadersDefaultCellStyle = dataGridViewCellStyle19;
            dgvPOSTax.ColumnHeadersHeight = 35;
            dgvPOSTax.ColumnHeadersHeightSizeMode = DataGridViewColumnHeadersHeightSizeMode.DisableResizing;
            dgvPOSTax.Columns.AddRange(dgvtxtSINO, dgvtxtTaxLedgerId, dgvtxtTaxName, dgvtxtTaxAmt, dgvtxttaxrate, dgvtxttax, dgvtxtTaxApplicableOn, dgvtxttaxCalculateMode, Column2, temp);
            dataGridViewCellStyle18.Alignment = DataGridViewContentAlignment.MiddleLeft;
            dataGridViewCellStyle18.BackColor = Color.FromArgb(224, 224, 224);
            dataGridViewCellStyle18.Font = new Font("Microsoft Sans Serif", 8.25f, FontStyle.Regular, GraphicsUnit.Point, 0);
            dataGridViewCellStyle18.ForeColor = Color.Black;
            dataGridViewCellStyle18.SelectionBackColor = Color.DarkGray;
            dataGridViewCellStyle18.SelectionForeColor = Color.Black;
            dataGridViewCellStyle18.WrapMode = DataGridViewTriState.False;
            dgvPOSTax.DefaultCellStyle = dataGridViewCellStyle18;
            dgvPOSTax.EnableHeadersVisualStyles = false;
            dgvPOSTax.GridColor = Color.DimGray;
            dgvPOSTax.Location = new Point(18, 421);
            dgvPOSTax.Margin = new Padding(3, 3, 3, 10);
            dgvPOSTax.Name = "dgvPOSTax";
            dgvPOSTax.ReadOnly = true;
            dgvPOSTax.RightToLeft = RightToLeft.No;
            dgvPOSTax.RowHeadersVisible = false;
            dgvPOSTax.Size = new Size(253, 97);
            dgvPOSTax.TabIndex = 13;
            dgvPOSTax.RowsAdded += dgvPOSTax_RowsAdded;
            dgvtxtSINO.HeaderText = "Sl No";
            dgvtxtSINO.Name = "dgvtxtSINO";
            dgvtxtSINO.ReadOnly = true;
            dgvtxtSINO.SortMode = DataGridViewColumnSortMode.NotSortable;
            dgvtxtTaxLedgerId.DataPropertyName = "ledgerId";
            dgvtxtTaxLedgerId.HeaderText = "ledgerId";
            dgvtxtTaxLedgerId.Name = "dgvtxtTaxLedgerId";
            dgvtxtTaxLedgerId.ReadOnly = true;
            dgvtxtTaxLedgerId.SortMode = DataGridViewColumnSortMode.NotSortable;
            dgvtxtTaxLedgerId.Visible = false;
            dgvtxtTaxName.DataPropertyName = "taxName";
            dataGridViewCellStyle17.Alignment = DataGridViewContentAlignment.MiddleCenter;
            dgvtxtTaxName.DefaultCellStyle = dataGridViewCellStyle17;
            dgvtxtTaxName.HeaderText = "Tax Name";
            dgvtxtTaxName.Name = "dgvtxtTaxName";
            dgvtxtTaxName.ReadOnly = true;
            dgvtxtTaxName.SortMode = DataGridViewColumnSortMode.NotSortable;
            dgvtxtTaxAmt.DataPropertyName = "taxAmount";
            dataGridViewCellStyle16.Alignment = DataGridViewContentAlignment.MiddleRight;
            dgvtxtTaxAmt.DefaultCellStyle = dataGridViewCellStyle16;
            dgvtxtTaxAmt.HeaderText = "Amount";
            dgvtxtTaxAmt.Name = "dgvtxtTaxAmt";
            dgvtxtTaxAmt.ReadOnly = true;
            dgvtxtTaxAmt.SortMode = DataGridViewColumnSortMode.NotSortable;
            dgvtxttaxrate.DataPropertyName = "rate";
            dgvtxttaxrate.HeaderText = "rate";
            dgvtxttaxrate.Name = "dgvtxttaxrate";
            dgvtxttaxrate.ReadOnly = true;
            dgvtxttaxrate.SortMode = DataGridViewColumnSortMode.NotSortable;
            dgvtxttaxrate.Visible = false;
            dgvtxttax.DataPropertyName = "taxId";
            dgvtxttax.HeaderText = "TaxId";
            dgvtxttax.Name = "dgvtxttax";
            dgvtxttax.ReadOnly = true;
            dgvtxttax.SortMode = DataGridViewColumnSortMode.NotSortable;
            dgvtxttax.Visible = false;
            dgvtxtTaxApplicableOn.DataPropertyName = "applicableOn";
            dgvtxtTaxApplicableOn.HeaderText = "ApplicableOn";
            dgvtxtTaxApplicableOn.Name = "dgvtxtTaxApplicableOn";
            dgvtxtTaxApplicableOn.ReadOnly = true;
            dgvtxtTaxApplicableOn.SortMode = DataGridViewColumnSortMode.NotSortable;
            dgvtxtTaxApplicableOn.Visible = false;
            dgvtxttaxCalculateMode.DataPropertyName = "calculatingMode";
            dgvtxttaxCalculateMode.HeaderText = "CalculatingMode";
            dgvtxttaxCalculateMode.Name = "dgvtxttaxCalculateMode";
            dgvtxttaxCalculateMode.ReadOnly = true;
            dgvtxttaxCalculateMode.SortMode = DataGridViewColumnSortMode.NotSortable;
            dgvtxttaxCalculateMode.Visible = false;
            Column2.DataPropertyName = "selectedtaxId";
            Column2.HeaderText = "selectedtaxId";
            Column2.Name = "Column2";
            Column2.ReadOnly = true;
            Column2.SortMode = DataGridViewColumnSortMode.NotSortable;
            Column2.Visible = false;
            temp.HeaderText = "temp";
            temp.Name = "temp";
            temp.ReadOnly = true;
            temp.SortMode = DataGridViewColumnSortMode.NotSortable;
            temp.Visible = false;
            lblLedgerTotal.AutoSize = true;
            lblLedgerTotal.ForeColor = Color.Black;
            lblLedgerTotal.Location = new Point(158, 525);
            lblLedgerTotal.Margin = new Padding(5);
            lblLedgerTotal.Name = "lblLedgerTotal";
            lblLedgerTotal.Size = new Size(37, 13);
            lblLedgerTotal.TabIndex = 1166;
            lblLedgerTotal.Text = "Total :";
            cbxPrintAfterSave.AutoSize = true;
            cbxPrintAfterSave.BackColor = Color.Transparent;
            cbxPrintAfterSave.ForeColor = Color.Black;
            cbxPrintAfterSave.Location = new Point(23, 536);
            cbxPrintAfterSave.Name = "cbxPrintAfterSave";
            cbxPrintAfterSave.Size = new Size(97, 17);
            cbxPrintAfterSave.TabIndex = 21;
            cbxPrintAfterSave.TabStop = false;
            cbxPrintAfterSave.Text = "Print after save";
            cbxPrintAfterSave.UseVisualStyleBackColor = false;
            cbxPrintAfterSave.KeyDown += cbxPrintAfterSave_KeyDown;
            lblTaxTotalAmount.Font = new Font("Microsoft Sans Serif", 9.75f, FontStyle.Bold, GraphicsUnit.Point, 0);
            lblTaxTotalAmount.ForeColor = Color.Brown;
            lblTaxTotalAmount.Location = new Point(188, 523);
            lblTaxTotalAmount.Margin = new Padding(5);
            lblTaxTotalAmount.Name = "lblTaxTotalAmount";
            lblTaxTotalAmount.Size = new Size(83, 16);
            lblTaxTotalAmount.TabIndex = 1169;
            lblTaxTotalAmount.Text = "00.00";
            lblTaxTotalAmount.TextAlign = ContentAlignment.MiddleRight;
            txtNarration.Location = new Point(281, 445);
            txtNarration.Margin = new Padding(5, 5, 5, 0);
            txtNarration.MaxLength = 5000;
            txtNarration.Multiline = true;
            txtNarration.Name = "txtNarration";
            txtNarration.Size = new Size(217, 73);
            txtNarration.TabIndex = 14;
            txtNarration.KeyDown += txtNarration_KeyDown;
            label26.AutoSize = true;
            label26.ForeColor = Color.Black;
            label26.Location = new Point(284, 425);
            label26.Margin = new Padding(5);
            label26.Name = "label26";
            label26.Size = new Size(50, 13);
            label26.TabIndex = 1161;
            label26.Text = "Narration";
            gbxAmountDetails.Controls.Add(groupBox2);
            gbxAmountDetails.Controls.Add(txtBalance);
            gbxAmountDetails.Controls.Add(lblBalance);
            gbxAmountDetails.Controls.Add(txtPaidAmount);
            gbxAmountDetails.Controls.Add(lblPaidAmount);
            gbxAmountDetails.Font = new Font("Arial", 9f, FontStyle.Bold, GraphicsUnit.Point, 0);
            gbxAmountDetails.ForeColor = Color.Maroon;
            gbxAmountDetails.Location = new Point(506, 424);
            gbxAmountDetails.Name = "gbxAmountDetails";
            gbxAmountDetails.Size = new Size(254, 94);
            gbxAmountDetails.TabIndex = 15;
            gbxAmountDetails.TabStop = false;
            gbxAmountDetails.Text = "Details";
            groupBox2.BackColor = Color.Black;
            groupBox2.ForeColor = Color.Black;
            groupBox2.Location = new Point(10, 17);
            groupBox2.Name = "groupBox2";
            groupBox2.Size = new Size(70, 1);
            groupBox2.TabIndex = 1180;
            groupBox2.TabStop = false;
            txtBalance.BackColor = Color.White;
            txtBalance.Font = new Font("Microsoft Sans Serif", 8.25f, FontStyle.Regular, GraphicsUnit.Point, 0);
            txtBalance.Location = new Point(103, 52);
            txtBalance.Margin = new Padding(5, 5, 5, 0);
            txtBalance.Name = "txtBalance";
            txtBalance.ReadOnly = true;
            txtBalance.Size = new Size(125, 20);
            txtBalance.TabIndex = 100;
            txtBalance.TextAlign = HorizontalAlignment.Right;
            lblBalance.AutoSize = true;
            lblBalance.Font = new Font("Microsoft Sans Serif", 8.25f, FontStyle.Regular, GraphicsUnit.Point, 0);
            lblBalance.ForeColor = Color.Black;
            lblBalance.Location = new Point(26, 56);
            lblBalance.Margin = new Padding(5);
            lblBalance.Name = "lblBalance";
            lblBalance.Size = new Size(46, 13);
            lblBalance.TabIndex = 1159;
            lblBalance.Text = "Balance";
            txtPaidAmount.Font = new Font("Microsoft Sans Serif", 8.25f, FontStyle.Regular, GraphicsUnit.Point, 0);
            txtPaidAmount.Location = new Point(103, 27);
            txtPaidAmount.Margin = new Padding(5, 5, 5, 0);
            txtPaidAmount.MaxLength = 10;
            txtPaidAmount.Name = "txtPaidAmount";
            txtPaidAmount.Size = new Size(125, 20);
            txtPaidAmount.TabIndex = 0;
            txtPaidAmount.Text = "0";
            txtPaidAmount.TextAlign = HorizontalAlignment.Right;
            txtPaidAmount.TextChanged += txtPaidAmount_TextChanged;
            txtPaidAmount.KeyDown += txtPaidAmount_KeyDown;
            txtPaidAmount.KeyPress += txtPaidAmount_KeyPress;
            txtPaidAmount.Leave += txtPaidAmount_Leave;
            lblPaidAmount.AutoSize = true;
            lblPaidAmount.Font = new Font("Microsoft Sans Serif", 8.25f, FontStyle.Regular, GraphicsUnit.Point, 0);
            lblPaidAmount.ForeColor = Color.Black;
            lblPaidAmount.Location = new Point(26, 31);
            lblPaidAmount.Margin = new Padding(5);
            lblPaidAmount.Name = "lblPaidAmount";
            lblPaidAmount.Size = new Size(67, 13);
            lblPaidAmount.TabIndex = 1157;
            lblPaidAmount.Text = "Paid Amount";
            cmbPricingLevel.DropDownStyle = ComboBoxStyle.DropDownList;
            cmbPricingLevel.FormattingEnabled = true;
            cmbPricingLevel.Location = new Point(576, 14);
            cmbPricingLevel.Margin = new Padding(5);
            cmbPricingLevel.Name = "cmbPricingLevel";
            cmbPricingLevel.Size = new Size(122, 21);
            cmbPricingLevel.TabIndex = 2;
            cmbPricingLevel.KeyDown += cmbPricingLevel_KeyDown;
            lblPricingLevel.AutoSize = true;
            lblPricingLevel.BackColor = Color.Transparent;
            lblPricingLevel.ForeColor = Color.Black;
            lblPricingLevel.Location = new Point(503, 18);
            lblPricingLevel.Margin = new Padding(5);
            lblPricingLevel.Name = "lblPricingLevel";
            lblPricingLevel.Size = new Size(68, 13);
            lblPricingLevel.TabIndex = 1171;
            lblPricingLevel.Text = "Pricing Level";
            dtpDate.Location = new Point(462, 16);
            dtpDate.Name = "dtpDate";
            dtpDate.Size = new Size(21, 20);
            dtpDate.TabIndex = 1175;
            dtpDate.ValueChanged += dtpDate_ValueChanged;
            txtDate.Location = new Point(327, 16);
            txtDate.Name = "txtDate";
            txtDate.Size = new Size(136, 20);
            txtDate.TabIndex = 1;
            txtDate.KeyDown += txtDate_KeyDown;
            txtDate.Leave += txtDate_Leave;
            label1.AutoSize = true;
            label1.ForeColor = Color.Red;
            label1.Location = new Point(405, 46);
            label1.Name = "label1";
            label1.Size = new Size(11, 13);
            label1.TabIndex = 1176;
            label1.Text = "*";
            label2.AutoSize = true;
            label2.ForeColor = Color.Red;
            label2.Location = new Point(705, 45);
            label2.Name = "label2";
            label2.Size = new Size(11, 13);
            label2.TabIndex = 1177;
            label2.Text = "*";
            label3.AutoSize = true;
            label3.ForeColor = Color.Red;
            label3.Location = new Point(491, 19);
            label3.Name = "label3";
            label3.Size = new Size(11, 13);
            label3.TabIndex = 1178;
            label3.Text = "*";
            base.AutoScaleDimensions = new SizeF(6f, 13f);
            base.AutoScaleMode = AutoScaleMode.Font;
            BackColor = Color.Gainsboro;
            base.ClientSize = new Size(992, 566);
            base.Controls.Add(label3);
            base.Controls.Add(label2);
            base.Controls.Add(label1);
            base.Controls.Add(dtpDate);
            base.Controls.Add(txtDate);
            base.Controls.Add(cmbPricingLevel);
            base.Controls.Add(lblPricingLevel);
            base.Controls.Add(gbxAmountDetails);
            base.Controls.Add(txtNarration);
            base.Controls.Add(label26);
            base.Controls.Add(lblTaxTotalAmount);
            base.Controls.Add(cbxPrintAfterSave);
            base.Controls.Add(lblLedgerTotal);
            base.Controls.Add(dgvPOSTax);
            base.Controls.Add(txtGrandTotal);
            base.Controls.Add(lblGrandTotal);
            base.Controls.Add(txtBillDiscount);
            base.Controls.Add(lblDiscount);
            base.Controls.Add(txtTotalAmount);
            base.Controls.Add(lblTotal);
            base.Controls.Add(lnklblRemove);
            base.Controls.Add(gbxDetails);
            base.Controls.Add(btnNewCounter);
            base.Controls.Add(cmbCounter);
            base.Controls.Add(lblCounter);
            base.Controls.Add(btnNewSalesAccount);
            base.Controls.Add(cmbSalesAccount);
            base.Controls.Add(lblsalesAccount);
            base.Controls.Add(btnNewLedger);
            base.Controls.Add(cmbSalesMan);
            base.Controls.Add(lblSalesMan);
            base.Controls.Add(lblDate);
            base.Controls.Add(btnNewSalesMan);
            base.Controls.Add(txtVoucherNo);
            base.Controls.Add(lblVoucherNo);
            base.Controls.Add(btnSave);
            base.Controls.Add(cmbCashOrParty);
            base.Controls.Add(btnClose);
            base.Controls.Add(btnDelete);
            base.Controls.Add(btnClear);
            base.Controls.Add(lblCashOrParty);
            base.Controls.Add(dgvPointOfSales);
            ForeColor = Color.Black;
            base.FormBorderStyle = FormBorderStyle.FixedSingle;
            base.Icon = (Icon)resources.GetObject("$this.Icon");
            base.KeyPreview = true;
            base.MaximizeBox = false;
            base.Name = "frmPOS";
            base.Padding = new Padding(15, 10, 15, 10);
            base.StartPosition = FormStartPosition.CenterScreen;
            Text = "POS";
            base.FormClosing += frmPOS_FormClosing;
            base.Load += frmPOS_Load;
            base.KeyDown += frmPOS_KeyDown;
            ((ISupportInitialize)dgvPointOfSales).EndInit();
            gbxDetails.ResumeLayout(false);
            gbxDetails.PerformLayout();
            ((ISupportInitialize)dgvPOSTax).EndInit();
            gbxAmountDetails.ResumeLayout(false);
            gbxAmountDetails.PerformLayout();
            base.ResumeLayout(false);
            base.PerformLayout();
        }

        #endregion

        private System.Windows.Forms.Button btnNewSalesMan;
        private System.Windows.Forms.TextBox txtVoucherNo;
        private System.Windows.Forms.Label lblVoucherNo;
        private System.Windows.Forms.Button btnSave;
        private System.Windows.Forms.ComboBox cmbCashOrParty;
        private System.Windows.Forms.Button btnClose;
        private System.Windows.Forms.Button btnDelete;
        private System.Windows.Forms.Button btnClear;
        private System.Windows.Forms.Label lblCashOrParty;
        private System.Windows.Forms.DataGridView dgvPointOfSales;
        private System.Windows.Forms.Label lblDate;
        private System.Windows.Forms.ComboBox cmbSalesMan;
        private System.Windows.Forms.Label lblSalesMan;
        private System.Windows.Forms.Button btnNewLedger;
        private System.Windows.Forms.Button btnNewSalesAccount;
        private System.Windows.Forms.ComboBox cmbSalesAccount;
        private System.Windows.Forms.Label lblsalesAccount;
        private System.Windows.Forms.Button btnNewCounter;
        private System.Windows.Forms.ComboBox cmbCounter;
        private System.Windows.Forms.Label lblCounter;
        private System.Windows.Forms.GroupBox gbxDetails;
        private System.Windows.Forms.TextBox txtBarcode;
        private System.Windows.Forms.Label lblBarcode;
        private System.Windows.Forms.Label lblItem;
        private System.Windows.Forms.TextBox txtProductCode;
        private System.Windows.Forms.Label lblProductcode;
        private System.Windows.Forms.ComboBox cmbItem;
        private System.Windows.Forms.ComboBox cmbBatch;
        private System.Windows.Forms.Label lblBatch;
        private System.Windows.Forms.ComboBox cmbRack;
        private System.Windows.Forms.Label lblRack;
        private System.Windows.Forms.ComboBox cmbGodown;
        private System.Windows.Forms.Label lblGodown;
        private System.Windows.Forms.TextBox txtGrossValue;
        private System.Windows.Forms.Label lblGrossValue;
        private System.Windows.Forms.TextBox txtRate;
        private System.Windows.Forms.Label lblRate;
        private System.Windows.Forms.ComboBox cmbUnit;
        private System.Windows.Forms.Label lblUnit;
        private System.Windows.Forms.TextBox txtQuantity;
        private System.Windows.Forms.Label lblQuantity;
        private System.Windows.Forms.TextBox txtTaxAmount;
        private System.Windows.Forms.Label lblTaxAmount;
        private System.Windows.Forms.ComboBox cmbTax;
        private System.Windows.Forms.Label lblTax;
        private System.Windows.Forms.TextBox txtNetAmount;
        private System.Windows.Forms.Label lblnetAmount;
        private System.Windows.Forms.TextBox txtAmount;
        private System.Windows.Forms.Label lblAmount;
        private System.Windows.Forms.TextBox txtDiscountAmount;
        private System.Windows.Forms.Label lblDiscountAmt;
        private System.Windows.Forms.TextBox txtDiscountPercentage;
        private System.Windows.Forms.Label lblDiscountPercentage;
        private System.Windows.Forms.Button btnAdd;
        private System.Windows.Forms.LinkLabel lnklblRemove;
        private System.Windows.Forms.TextBox txtTotalAmount;
        private System.Windows.Forms.Label lblTotal;
        private System.Windows.Forms.TextBox txtBillDiscount;
        private System.Windows.Forms.Label lblDiscount;
        private System.Windows.Forms.TextBox txtGrandTotal;
        private System.Windows.Forms.Label lblGrandTotal;
        private System.Windows.Forms.DataGridView dgvPOSTax;
        private System.Windows.Forms.Label lblLedgerTotal;
        private System.Windows.Forms.CheckBox cbxPrintAfterSave;
        private System.Windows.Forms.Label lblTaxTotalAmount;
        private System.Windows.Forms.TextBox txtNarration;
        private System.Windows.Forms.Label label26;
        private System.Windows.Forms.GroupBox gbxAmountDetails;
        private System.Windows.Forms.TextBox txtBalance;
        private System.Windows.Forms.Label lblBalance;
        private System.Windows.Forms.TextBox txtPaidAmount;
        private System.Windows.Forms.Label lblPaidAmount;
        private System.Windows.Forms.ComboBox cmbPricingLevel;
        private System.Windows.Forms.Label lblPricingLevel;
        private System.Windows.Forms.DateTimePicker dtpDate;
        private System.Windows.Forms.TextBox txtDate;
        private System.Windows.Forms.Label label1;
        private System.Windows.Forms.Label label2;
        private System.Windows.Forms.Label label3;
        private System.Windows.Forms.Label lblUnitConversionId;
        private System.Windows.Forms.Label lblUnitConversionRate;
        private System.Windows.Forms.Label lblUnitConversion;
        private System.Windows.Forms.DataGridViewTextBoxColumn dgvtxtSINO;
        private System.Windows.Forms.DataGridViewTextBoxColumn dgvtxtTaxLedgerId;
        private System.Windows.Forms.DataGridViewTextBoxColumn dgvtxtTaxName;
        private System.Windows.Forms.DataGridViewTextBoxColumn dgvtxtTaxAmt;
        private System.Windows.Forms.DataGridViewTextBoxColumn dgvtxttaxrate;
        private System.Windows.Forms.DataGridViewTextBoxColumn dgvtxttax;
        private System.Windows.Forms.DataGridViewTextBoxColumn dgvtxtTaxApplicableOn;
        private System.Windows.Forms.DataGridViewTextBoxColumn dgvtxttaxCalculateMode;
        private System.Windows.Forms.DataGridViewTextBoxColumn Column2;
        private System.Windows.Forms.DataGridViewTextBoxColumn temp;
        private System.Windows.Forms.DataGridViewTextBoxColumn dgvtxtSlNo;
        private System.Windows.Forms.DataGridViewTextBoxColumn rowId;
        private System.Windows.Forms.DataGridViewTextBoxColumn dgvtxtProductId;
        private System.Windows.Forms.DataGridViewTextBoxColumn dgvtxtProductCode;
        private System.Windows.Forms.DataGridViewTextBoxColumn dgvtxtProductName;
        private System.Windows.Forms.DataGridViewTextBoxColumn dgvtxtQuantity;
        private System.Windows.Forms.DataGridViewTextBoxColumn dgvtxtUnit;
        private System.Windows.Forms.DataGridViewTextBoxColumn dgvtxtRate;
        private System.Windows.Forms.DataGridViewTextBoxColumn dgvtxtGrossValue;
        private System.Windows.Forms.DataGridViewTextBoxColumn dgvtxtDiscount;
        private System.Windows.Forms.DataGridViewTextBoxColumn dgvtxtNetAmount;
        private System.Windows.Forms.DataGridViewTextBoxColumn dgvtxtTaxPercentage;
        private System.Windows.Forms.DataGridViewTextBoxColumn dgvtxttaxid;
        private System.Windows.Forms.DataGridViewTextBoxColumn dgvtxtTaxAmount;
        private System.Windows.Forms.DataGridViewTextBoxColumn dgvtxtTotalAmount;
        private System.Windows.Forms.DataGridViewTextBoxColumn dgvtxtBatchId;
        private System.Windows.Forms.DataGridViewTextBoxColumn dgvtxtBatchno;
        private System.Windows.Forms.DataGridViewTextBoxColumn dgvtxtRackId;
        private System.Windows.Forms.DataGridViewTextBoxColumn dgvtxtRackName;
        private System.Windows.Forms.DataGridViewTextBoxColumn dgvtxtGodownId;
        private System.Windows.Forms.DataGridViewTextBoxColumn dgvtxtGodownName;
        private System.Windows.Forms.DataGridViewTextBoxColumn dgvtxtUnitId;
        private System.Windows.Forms.DataGridViewTextBoxColumn dgvtxtunitconversionId;
        private System.Windows.Forms.DataGridViewTextBoxColumn dgvtxtBarcode;
        private System.Windows.Forms.DataGridViewTextBoxColumn dgvtxtDiscountPercentage;
        private System.Windows.Forms.DataGridViewTextBoxColumn dgvtxtSalesDetailsId;
        private GroupBox groupBox1;

        private GroupBox groupBox2;
    }
}